name: say-hello
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps: # список шагов, которые надо выполнить
      # экшен — выполняет какую-то задачу
      # checkout — клонирует репозиторий
      - uses: actions/checkout@v3
      - name: run setup
        run: make setup
      - run: make test
      - run: make lint
